FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /build
COPY . .
RUN ls -al /opt
RUN ls -al /workspace
RUN ls -al /workspace/output/source
WORKDIR /build
RUN mvn clean install -DskipTests

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1295
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --from=build /build/target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
